from __future__ import annotations

CONTROL_SIZE = 0x10
PING_SIZE = 0x15
OPENCLOSE_SIZE = 0x16
AUDIO_SIZE = 0x18
CIV_SIZE = 0x15
DATA_SIZE = 0x15
TOKEN_SIZE = 0x40
STATUS_SIZE = 0x50
LOGIN_RESPONSE_SIZE = 0x60
LOGIN_SIZE = 0x80
CONNINFO_SIZE = 0x90
CAPABILITIES_SIZE = 0x42
RADIO_CAP_SIZE = 0x66
GUIDLEN = 16

SCRIPT_VERSION = "v103"
DEFAULT_CONTROL_PORT = 50001
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_RX_CODEC = 0x04  # LPCM16 fallback used by the IC-705 LAN audio path
DEFAULT_TX_CODEC = 0x04

# Conservative runtime constants.  Keeping these named makes future tuning safer
# than scattering magic values through audio, CAT and shutdown paths.
TX_AUDIO_MAX_PAYLOAD = 1364
TX_AUDIO_BLOCK_MS = 0.020
REAL_CAT_CACHE_TTL = 0.0
TOKEN_REMOVAL_ATTEMPTS = 3
TOKEN_REMOVAL_ACK_TIMEOUT = 0.35
CONTROL_PRE_TOKEN_DRAIN_TIMEOUT = 0.15
STREAM_RETRY_BASE_BACKOFF = 0.75
STREAM_RETRY_BACKOFF_STEP = 0.35
STREAM_RETRY_CONTROL_SERVICE_INTERVAL = 0.05
STREAM_RELOGIN_BACKOFF = 1.50
STREAM_RELOGIN_BACKOFF_STEP = 0.75
LOGIN_RETRY_ATTEMPTS = 3
LOGIN_RETRY_BACKOFF = 1.25
LOGIN_RESPONSE_TIMEOUT = 5.0
CONTROL_DISCOVERY_TIMEOUT = 6.0
CONTROL_READY_TIMEOUT = 2.0
CIV_SET_ACK_TIMEOUT = 0.25
CIV_READ_TIMEOUT = 1.20
CIV_PTT_READ_TIMEOUT = 0.80
CIV_FIRST_READ_RETRY_TIMEOUT = 1.50

PTT_OFF_RECOVERY_ATTEMPTS = 3
PTT_OFF_RECOVERY_DELAY = 0.08
STATION_HEALTH_INTERVAL = 10.0
STATION_CONTROL_PING_INTERVAL = 1.0
STATION_IDLE_CONTROL_INTERVAL = 2.0
STATION_TOKEN_KEEPALIVE_INTERVAL = 15.0
SHUTDOWN_CONTROL_HEX_LIMIT = 96

# Credential lookup data is loaded by icom_lan.auth from
# docs/provenance/icom_lan_credential_encoding/generated_lookup.json.


